spring:
  application:
    name: credit-service
  profiles:
    active: dev
  datasource:
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5430/credit_db
  liquibase:
    change-log: classpath:db/migrations.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topics:
  overdue:
    name: t.credit.overdue


server:
  port: 8081



---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

credit:
  rate:
    fixed: 0.05
    floating: 0.02