spring:
  application:
    name: credit-service

server:
  port: 8081

  datasource:
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/credit_db

  liquibase:
    change-log: classpath:db/migrations.yaml

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

credit:
  rate:
    fixed: 0.05
    floating: 0.02