spring:
  kafka:
    consumer:
      group-id: "default"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: localhost:9092,localhost:9094
      properties:
        spring:
          json:
            trusted:
              packages: com.banksystem.overdue.dto

topic:
  name: t.credit.overdue