spring:
  application:
    name: loan-service
  config:
    import: optional:config-server:http://localhost:8888/
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
  cloud:
    config:
      import-check:
        enabled: false
---
spring:
  profiles:
    active: docker
  config:
    import: optional:config-server:http://config:8888/
  datasource:
    url: jdbc:postgresql://postgres:5432/loan_db
  kafka:
    bootstrap-servers: kafka:9092, kafka:9094

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka
