server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: rate-service
          uri: lb://rate-service
          predicates:
            - Path=/rate-service/api/v1/rate/**
          filters:
            - StripPrefix=1
      default-filters:
        - TokenRelay

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles:
    active: docker

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka
